config/routes.rb
Rails.application.routes.draw do
  
  resources :teams
  resources :comments
  resources :movies do
    member { post 'checkout' }
    member { post 'checkin' }
    
  end
  
  authenticated :user do
    root to: "movies#index", as: :authenticated_root
  end
  
  unauthenticated do
    root to: 'visitors#index'
  end

  devise_for :users, :controllers => { registrations: 'registrations' }  
  resources :users  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :checkout, :checkin]
  before_action :get_cart
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @current_user = current_user
    #@movies = Movie.sorted
    @movies = current_user.team.movies.sorted
    if !@checkout_warning.nil? && !@checkout_warning.empty?
      flash[:warning] = @checkout_warning
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @current_user = current_user

    @comments = @movie.comments.all
    @comment = @movie.comments.build

    if !@movie.override_checkout.nil? && @movie.override_checkout != ""
      @movie_checkout_status = "Checked out to #{@movie.override_checkout}"
    else 

      if !@movie.checked_out_to_id.nil?
        if @movie.checked_out_to_id == current_user.id
          @movie_checkout_status = "You currently have this movie"
        else
          checked_out_to = User.find(@movie.checked_out_to_id).name
          @movie_checkout_status = "Checked out to #{checked_out_to}" 
        end
      else
        @movie_checkout_status = "Available!" 
      end
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @checkout_users = User.for_team(current_user.team_id)
  end

  # GET /movies/1/edit
  def edit
    @checkout_users = User.for_team(current_user.team_id)  
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    #all new movies created under team of current person (who is an admin because they CAN create)
    @movie.team_id = current_user.team_id

    @current_checkout = 0
    if @movie.rating.nil?
      @movie.rating = 0
    end
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        @checkout_users = User.for_team(current_user.team_id)  
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update

    if @movie.rating.nil?
      @movie.rating = 0
    end

    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        #dev pro-tip: if update fails, it will rerender form but not call 
        #             edit controller method, so be sure to supply
        #             any needed instance vars before re-rendering:
        @checkout_users = User.for_team(current_user.team_id)
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def checkout
    if @movie.update(:checked_out_to => current_user)
      redirect_to @movie, notice: 'Movie was successfully checked out to you!' 
    else
      redirect_to @movie, notice: 'Error unable to checkout movie' 
    end    
  end

  def checkin
    
    if @movie.update(:checked_out_to => nil)
      redirect_to @movie, notice: 'Movie was successfully returned!' 
    else
      redirect_to @movie, notice: 'Error unable to return movie' 
    end
    
  end
  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Get Current count
    def get_cart
      @checkout_count = Movie.checkout_count_for_user current_user
      @checkout_limit = current_user.team.checkout_limit || 3
      @checkout_status = "(#{@checkout_count} of #{@checkout_limit} movies checked out)"
      @checkout_warning = ""
      if @checkout_count == @checkout_limit
        @checkout_warning = "Warning: you cannot checkout any more movies"
      elsif @checkout_count > @checkout_limit
        @checkout_warning = "You have checked out more movies than allowed!"
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :rating, :runtime, :released, :url, :checked_out_to_id, :override_checkout, :team_id)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default devise-bs">
    <div class="panel-heading">
      <h4>
        <%= form.label :title %>
      </h4>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :movie_title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :movie_description, rows:4, class: 'form-control'  %>
      </div>

      <div class="form-group">
        <%= form.label :rating %>
        <%= form.number_field :rating, id: :movie_rating, class: 'form-control'  %>
      </div>

      <div class="form-group">
        <%= form.label :runtime %>
        <%= form.number_field :runtime, id: :movie_runtime, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :released %>
        <%= form.date_field :released, id: :movie_released, class: 'form-control'  %>
      </div>

      <div class="form-group">
        <%= form.label :url %>
        <%= form.text_field :url, id: :movie_url, class: 'form-control'  %>
      </div>
      <% if @checkout_users.nil? %>
        <p> Checkout Users is nil - why!?! </p>
      <% else %>
        <div class="form-group">
          <%= form.label :checed_out_to %> &nbsp; <i>Who currently has this movie checked out</i>        
          <%= form.select :checked_out_to_id, options_for_select(@checkout_users.map{ |s| [s.name, s.id] }, @movie.checked_out_to_id), :include_blank => true, :id => 'checked_out_to_id' %>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :override_checkout %> &nbsp; <i>To indicate checkout to someone not in the system (will override dropdown above)</i>        
        <%= form.text_field :override_checkout, id: :movie_override_checkout, class: 'form-control'  %>
      </div>


  <div class="actions" >
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie, :class => 'btn btn-default' %> 
<%= link_to 'Back to List', movies_path, :class => 'btn btn-default' %>
<%= link_to 'DELETE', movie_path(@movie), :method => :delete, data: { confirm: "Are you ABSOLUTELY sure you want to delete this move (and comments)?" }, :class => 'btn btn-danger' %>

app/views/movies/index.html.erb
<div><h1><%= image_tag '/assets/kentflix_logo_sm.png', :style => "align:left" %> &nbsp;Movies</h1></div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th class="hidden-xs">Description</th>
        <th class="hidden-xs" width="100px">Rating</th>
        <th>Borrower</th>
      </tr>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><b><%= link_to movie.title, movie %></b></td>
          <td class="hidden-xs"><i><%= raw movie.description %></i></td>
          <td class="hidden-xs">
          <% if !movie.rating.nil? %>  
            <% for i in 0...movie.rating do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
          <% end %>
          </td>
          <% if movie.override_checkout.nil? || movie.override_checkout == "" %>
          <td class="tags"><%= movie.checked_out_to.nil? ? link_to("Available!", movie, :class=>"success") : link_to(movie.checked_out_to.name, movie, :class=>"warning") %></td>          
          <% else %>
          <td class="tags"><%= link_to(movie.override_checkout, movie, :class=>"warning") %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</table>
<br>
<% if @current_user.admin %>
<%= link_to 'New Movie', new_movie_path, :class => 'btn btn-primary' %>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h4>
      <%= link_to @movie.title, @movie.url %>
    </h4>
  </div>
  <div class="panel-body">
    <div class="form-group">
      <p>
        <strong>Description:</strong>
        <%= raw @movie.description %>
      </p>
    </div>
    <div class="form-group">
      <p>
        <strong>Rating:</strong>
        <% if !@movie.rating.nil? %>  
          <% for i in 0...@movie.rating do %>
            <i class="fa fa-star" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="form-group">
      <p>
        <strong>Runtime:</strong>
        <%= @movie.runtime %> minutes.
      </p>
    </div>      
    <div class="form-group">
      <p>
        <strong>Released:</strong>
        <%= @movie.released %>
      </p>
    </div>            
    <div class="form-group">
      <p>
        <% if @movie_checkout_status == "Available!" %>
          <%= button_to "Check Out!", { :controller => "movies", :action => "checkout"}, class: 'btn btn-primary' %>
        <% elsif @movie_checkout_status == "You currently have this movie" %>
          <%= button_to "Return Movie", { :controller => "movies", :action => "checkin"}, class: 'btn btn-primary' %>
        <% else %>
          <strong>
            <%= @movie_checkout_status %>
          </strong>
          <br/>
          <i>Coming soon: add yourself to waiting list</i>
        <% end %>
        <br/>
        <% if @current_user.admin %>
          <%= link_to 'Edit', edit_movie_path(@movie), :class => 'btn btn-default' %> 
        <% end %>
        <%= link_to 'Back to list', movies_path, :class => 'btn btn-default' %> 
      </p>
    </div>               
  </div>
</div>

<div class="col-md-10 col-sm-10">
  <% @comments.each do |comment| %>
  <div class="panel panel-default arrow left">
    <div class="panel-body">
      <header class="text-left">
        <strong class="pull-left primary-font"><i class="fa fa-user"></i> &nbsp; <%= comment.get_create_user %></strong>
        <small class="pull-right text-muted">
           <span class="fa fa-clock-o"></span><%= comment.created_at.to_formatted_s(:short) %></small>
        </br>
      </header>
      <div class="comment-post">
        <p>
          <%= comment.body %>
        </p>
      </div>
      <% if @current_user.name == comment.get_create_user %>
        <p class="text-right"><%= link_to raw('<i class="fa fa-trash"></i> Delete'), comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></p>
      <% end %>
    </div>  
  </div>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
</div>
<br/>